name: Check RDV CNI

on:
  schedule:
    # Tous les jours à 09:00 Paris (UTC+1/UTC+2)
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  check_rdv:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright requests
        playwright install

    - name: Run consulat script
      env:
        MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
        MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
        MAIL_TO: ${{ secrets.MAIL_TO }}
      run: python consulat.py
