name: Consulat RDV Checker

on:
  workflow_dispatch: # pour lancer manuellement
  schedule:
    - cron: '0 9 * * 1,3,5' # chaque lundi, mercredi, vendredi à 09:00 UTC

jobs:
  check_rdv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests playwright

      - name: Install Playwright browsers
        run: |
          python -m playwright install

      - name: Run consulat script
        run: python consulat_senegal_date_checker/consulat.py
        env:
          MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
          MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
          MAIL_TO: ${{ secrets.MAIL_TO }}
