name: Consulat Senegal Date Checker

on:
  schedule:
    - cron: "0 7 * * *"   # 08:00 Paris = 07:00 UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run consulat script
        working-directory: consulat_senegal_date_checker
        env:
          MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
          MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
          MAILGUN_RECIPIENT: ${{ secrets.MAILGUN_RECIPIENT }}
        run: python consulat.py
